### ISSUE TITLE
Some minor clarifications in the documentation

### ISSUE THREAD

**Issue by pstansell** [Nth-iteration-labs/contextual#11]
This is quite a minor point, but the documentation from `?LinUCBGeneralPolicy` mentions "Algorithm 1 LinUCB" in the paper by Lihong Li et all (2010), whereas the documentation from `?LinUCBDisjointPolicy` does not.  However, comparing Algorithm 1 from the paper with your code it seems that `LinUCBDisjointPolicy` is exactly "Algorithm 1 LinUCB" from the paper, whereas `LinUCBGeneralPolicy` is similar but not the same (more like the other part of the LinUCB hydrid model that is not in LinUCBDisjointPolicy).  If I'm right, I think it would helpful for the documentation to state explicitly that `LinUCBDisjointPolicy` is "Algorithm 1 LinUCB" from Li's paper.

Also, the description for the documentation from `?LinUCBHybridPolicy` refers to `LinUCBHybridOptimizedPolicy`.  I guess that both `LinUCBHybridPolicy` and `LinUCBHybridOptimizedPolicy` are exactly "Algorithm 2 LinUCB with hybrid linear models" from Li's paper.  Again, if I'm correct, I think it would helpful to state this explicitly in the documentation.

**Comment by robinvanemden** [comment]
Thanks, @pstansell ! You are correct - I have made the requested changes to the documentation.
