### ISSUE TITLE
How to change the discount factor?

### ISSUE THREAD

**Issue by b-rodrigues** [Nth-iteration-labs/contextual#13]
Hi,

this may be a stupid question but I don't see how I can choose the discount factor of the bandits? What value is it by default?

Thanks

**Comment by robinvanemden** [comment]
Do you refer to a discounting factor as used in non-stationary bandit problems? `contextual` currently focuses on stationary bandit problems - but should not be hard to implement both non-stationary type bandits and discounting policies. See for instance https://github.com/Nth-iteration-labs/contextual/blob/master/demo/demo_subsubclass.R for an annealing bandit policy to get you started.

**Comment by robinvanemden** [comment]
I will close the issue due to inactivity for now. Feel free to reopen the issue if and when you consider this question still unanswered, though!
