### ISSUE TITLE
Minor update required for EpsilonFirstPolicy object input in documentation article

### ISSUE THREAD

**Issue by kfoofw** [Nth-iteration-labs/contextual#14]
Hi there, I am really excited to use your package to learn more about contextual bandit simulations. 

I was trying out a particular documentation article (https://nth-iteration-labs.github.io/contextual/articles/introduction.html) and I think there might be some syntax issue with the parameter input for EpsilonFirstPolicy object.

```
# Initialize an EpsilonFirstPolicy with a 100 step exploration period.
ef_policy <- EpsilonFirstPolicy$new(first = 100)
```

I believe it should be `time_steps = 100` instead of `first = 100` based on the function help documentation as shown:
```
#Usage
policy <- EpsilonFirstPolicy(epsilon = 0.1, N = 1000, time_steps = NULL)

#Arguments
epsilon
numeric; value in the closed interval (0,1] that sets the number of time steps to explore through epsilon * N.

N
integer; positive integer which sets the number of time steps to explore through epsilon * N.

time_steps
integer; positive integer which sets the number of time steps to explore - can be used instead of epsilon and N.


```

Thanks for putting up such a complete package!

**Comment by robinvanemden** [comment]
Thanks - you are absolutely right! I fixed this in my latest commit.
