### ISSUE TITLE
minor correction for statement in demo "Demo: Bandits, Propensity Weighting & Simpson’s Paradox in R"

### ISSUE THREAD

**Issue by kfoofw** [Nth-iteration-labs/contextual#21]
Hi Robin, I was looking through your recent demo on the Simpson's paradox and I realised that there might be a wrong/false statement. 

![contextual](https://user-images.githubusercontent.com/7871453/80934816-bcbb2b00-8d7e-11ea-9241-c3377e7db5e3.png)

Instead of " **you’d falsely conclude Sports is more popular then Movies, overall**", I think the statement should be alluding to the wrong conclusion that "**Movies is more popular than Sports**". 

Thanks for coming up with the awesome package!

**Comment by robinvanemden** [comment]
Hi @kfoofw - thanks for submitting this issue! You are absolutely right - that line should read "Movies is more popular than Sports". I fixed this in the source code - I will update the package's site and docs later this week.

**Comment by robinvanemden** [comment]
I have commited a new version of contextual to CRAN just now!
