### ISSUE TITLE
Confusing assignments in method get_reward for OfflineDoublyRobustBandit

### ISSUE THREAD

**Issue by leferrad** [Nth-iteration-labs/contextual#23]
I'm studying contextual bandits so I found very useful this library to understand the algorithms involved. In particular, I was trying to review the implementation of OfflineDoublyRobustBandit, and I got confused about the definition of "inverted" parameter in [these lines](https://github.com/Nth-iteration-labs/contextual/blob/master/R/bandit_offline_doubly_robust.R#L47-L54 ):

```R
        if (self$inverted) p <- 1 / p
        if (self$threshold > 0) {
          if (isTRUE(self$inverted))  p <- 1 / p
          p <- 1 / max(p,self$threshold)
        } else {
          if (!isTRUE(self$inverted)) p <- 1 / p
        }
```
I think the [last line](https://github.com/Nth-iteration-labs/contextual/blob/master/R/bandit_offline_doubly_robust.R#L53) could be a bug (since it inverts p even if "inverted" is FALSE), and it seems like this could be done with something simpler like: 

```R
        if (self$threshold > 0) {
          p <- 1 / max(p,self$threshold)
        } else {
          if (isTRUE(self$inverted)) p <- 1 / p
        }
```
Could someone confirm if that is a bug or not? And what's the logic about that parameter? Thanks in advance.

**Comment by robinvanemden** [comment]
I already though of `OfflineDoublyRobustBandit` as somewhat over-engineered. I think it certainly warrants some refactoring. I will check my notes with regards to the "inverted" parameter later this week, and see if I am able to clarify its use. It may also prove to be a bug, of course. Either way, thanks for looking into this - much appreciated!

**Comment by robinvanemden** [comment]
Hi @leferrad 
Sorry for the delay - I was finally able to go over the OfflineDoublyRobustBandit code today.
I found we used the "inverted" argument to fix the data of one particular dataset. So it makes sense to just remove it. This makes the code much cleaner:

```R
        p = max(private$p[index], self$threshold) # when threshold 0 (default)
                                                  # p = private$p[index]
        w <- 1 / p
```

See commit:

https://github.com/Nth-iteration-labs/contextual/commit/a2ffe1728acb7133b2a233e2b5ba0da873b5ae18
