### ISSUE TITLE
Possible bug in Exp3Policy

### ISSUE THREAD

**Issue by leferrad** [Nth-iteration-labs/contextual#24]
I was reviewing the implementation of Exp3 algorithm in [this function](https://github.com/Nth-iteration-labs/contextual/blob/master/R/policy_mab_exp3.R#L16-L24), with the help of the formula posted in [this link](https://jeremykun.com/2013/11/08/adversarial-bandits-and-the-exp3-algorithm/). I think the last statement of the formula is wrong, since it is only updating the last element of `probs` and not all the elements (seems like it should be inside the loop):
```R
    get_action = function(t, context) {
      probs <- rep(0.0, context$k)
      for (i in 1:context$k) {
         probs[i] <- (1 - gamma) * (self$theta$weight[[i]] / sum_of(self$theta$weight))
      }
      inc(probs[i])  <- ((gamma) * (1.0 / context$k))  # <--------
      action$choice  <- categorical_draw(probs)
      action
    },
```
So I think it must be corrected as it follows:

```R
    get_action = function(t, context) {
      probs <- rep(0.0, context$k)
      for (i in 1:context$k) {
         probs[i] <- (1 - gamma) * (self$theta$weight[[i]] / sum_of(self$theta$weight))
         inc(probs[i])  <- ((gamma) * (1.0 / context$k))  # <-------
      }  
      action$choice  <- categorical_draw(probs)
      action
    },
```

Could you confirm this is a bug? Then I can make a simple PR to correct it.

**Comment by robinvanemden** [comment]
Hi @leferrad - thanks! You are absolutely right. That line of code somehow landed outside of the brackets. A PR would be super!

**Comment by leferrad** [comment]
Great! I will do that then. I could not find a test related to that policy, so I can either extend the file `tests/testthat/test_policies.R` with a test for Exp3Policy or create a new file `tests/testthat/test_policy_exp3.R` just for that. Let me know what works best for you.

**Comment by robinvanemden** [comment]
Hi @leferrad - I just added you fix to and related updates to the test in [this commit](https://github.com/Nth-iteration-labs/contextual/commit/0424c54f8a1c7ae7adb5106b10a9b7af140fe388).

It will be part of our next [CRAN package release](https://github.com/Nth-iteration-labs/contextual/commit/0424c54f8a1c7ae7adb5106b10a9b7af140fe388#diff-8312ad0561ef661716b48d09478362f3) - thanks again!
