### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by jaredlander** [Nth-iteration-labs/contextual#3]
In your Section 7.1 of your paper you read in data from [https://raw.githubusercontent.com/Nth-iteration-labs/contextual_data/master/data_cmab_basic/dataset.txt](https://raw.githubusercontent.com/Nth-iteration-labs/contextual_data/master/data_cmab_basic/dataset.txt). However, trying to read it with `fread` and visiting it in a browser result in a 404 error.

Without the data I am unable to reproduce that part of the paper. Are there plans to restore the data or is there another location?

**Comment by jaredlander** [comment]
Following your path of footnotes I found the original link from [Columbia](http://www.cs.columbia.edu/~jebara/6998/dataset.txt). Perhaps the githubusercontent link can redirect there or the paper updated?

**Comment by robinvanemden** [comment]
Thank you for checking out the paper and the package! The paper itself will be updated within the next month - it is not yet fully up to date with the latest version of the package. I will make sure to change the link as well!
