### ISSUE TITLE
Example of customized context-free bandits

### ISSUE THREAD

**Issue by kasakh** [Nth-iteration-labs/contextual#4]
I have offline data available in the following format:
time | reward_arm1 | reward_arm2| reward_arm3|
This is not a contextual bandit case as there is only reward of each arm at time t.  I want to implement UCB1, UCB2 and other context-free algorithms on this data.  I searched for a demo on context free custom data however, I could not find any. So, I am creating a custom context-free bandit from one of the demos available. 

@robinvanemden 
For example in your [myocardial example](https://github.com/Nth-iteration-labs/contextual/blob/44206c78fa6ca19da221e4372895699a95606ae2/demo/offline_bandit_evaluations/demo_offline_bootstrap_replay.R), there are two arms - treatment and no_treatment - each has its own reward. The computed R1 and R2 in the example can be the rewards of the arms.  

I tried to create a new dataset with just these two columns R1 and R2 as follows: 

```
# Import myocardial infection dataset

url             <- "http://d1ie9wlkzugsxr.cloudfront.net/data_propensity/myocardial_propensity.csv"
data            <- fread(url)

simulations     <- 1
horizon         <- nrow(data)


data$trt        <- data$trt + 1


data$alive      <- abs(data$death - 1)


f                <- alive ~ age + risk + severity

model_f          <- function(arm) glm(f, data=data[trt==arm], family=binomial(link="logit"), y=F, model=F)
arms             <- sort(unique(data$trt))
model_arms       <- lapply(arms, FUN = model_f)

predict_arm      <- function(model) predict(model, data, type = "response")
r_data           <- lapply(model_arms, FUN = predict_arm)
r_data           <- do.call(cbind, r_data)
colnames(r_data) <- paste0("R", (1:max(arms)))
data             <- cbind(data,r_data)

# extracting only R1 and R2
data        <- data[,8:9]

```

I am trying to creating a bandit out of this data and run the algorithms but it does not work.

```
# New-changed formula

#f                <- alive ~ trt | age + risk + severity | R1 + R2
#2 
f                <- alive ~ R1 + R2

#bandit           <- OfflineDirectMethodBandit$new(formula = f, data = data)
bandit           <- OfflineDirectMethodBandit$new( data = data)

# Define agents.

#agents      <- list(Agent$new(LinUCBDisjointOptimizedPolicy$new(0.2), bandit, "LinUCB"))
agents      <- list(Agent$new(UCB1Policy$new(), bandit, "UCB"))


simulation  <- Simulator$new(agents = agents, simulations = simulations, horizon = horizon, do_parallel = FALSE)


sim  <- simulation$run()


plot(sim, type = "cumulative", regret = FALSE, rate = TRUE, legend_position = "bottomright")

```

Especially, the simulation step does not run. Can you please point me towards a minimum working example of running UCB1, or UCB2 on a context-free custom data?

**Comment by g0ulash** [comment]
Do you still need help with this?

**Comment by kasakh** [comment]
@g0ulash Yeah, I have not figured out how to implement it.

**Comment by g0ulash** [comment]
First of all, which method do you want to use:

- Direct Method
- Inverse Propensity Weighting (either using propensity score or the Li. method when data is uniform randomly generated)
- Doubly Robust

Based on this, I can try and give you a minimal working example.

**Comment by robinvanemden** [comment]
Seeing there has been no response to @g0ulash since the 16th of December, I close this issue for now. Feel free to re-open if you have any further questions!
