### ISSUE TITLE
abline() does not draw lines where expected

### ISSUE THREAD

**Issue by pstansell** [Nth-iteration-labs/contextual#7]
Thanks for your really quick fix last time.  Here I'm having a problem with plotting.  Using `abline()` does not draw a line where expected.  Also, using `grid()` does not give the expected results.

Start `R` and run the example from `?EpsilonGreedyPolicy` with the following:
```
library(contextual)

horizon     <- 100L
simulations <- 100L
weights     <- c(0.9, 0.1, 0.1)
policy      <- EpsilonGreedyPolicy$new(epsilon = 0.1)
bandit      <- BasicBernoulliBandit$new(weights = weights)
agent       <- Agent$new(policy, bandit)
history     <- Simulator$new(agent, horizon, simulations, do_parallel = FALSE)$run()
plot(history, type = "cumulative")
abline(h=0, col=3, lwd=4)
abline(h=1, col=3, lwd=4)
abline(v=0, col=3, lwd=4)
abline(v=1, col=3, lwd=4)
grid()
```

In the image below, the green lines show the locations of 0 and 1 according to `abline`.  The misalignment with the axis labels makes it difficult to use `abline` on `contextual` plots.  Also, the faint dashed lines of `grid` do not align with the axis ticks.

![my_plot_name](https://user-images.githubusercontent.com/16215335/71206408-5edce980-229c-11ea-94cf-03b7e437e62d.png)

```
sessionInfo()
## R version 3.5.2 (2018-12-20)
## Platform: x86_64-redhat-linux-gnu (64-bit)
## Running under: CentOS release 6.10 (Final)
##
## other attached packages:
## [1] data.table_1.11.4  contextual_0.9.8.2
```

**Comment by robinvanemden** [comment]
By default, the contextual `plot()` function sets a few graphical parameters using `par()`. It is possible that these customisations interfere with your abline and grid directives. You could try whether setting the plot function's `no_par` argument to `TRUE` fixes your issues.

If not, I will certainltly try to find a solution for you sometime next week (as I am currently traveling).

**Comment by pstansell** [comment]
Your suggestion works.  If I replace the plot command from above with
```
plot(history, type = "cumulative", no_par = TRUE)
```
then both `abline` and `grid` work as expected.  Thanks very much for the tip!

I just realised that I can see the help on `contextual`'s plot command using `?Plot`.
