### ISSUE TITLE
Setting random seed outside of Simulator

### ISSUE THREAD

**Issue by pstansell** [Nth-iteration-labs/contextual#9]
Hello Robin, I wanted to point out the following as it confused me for a while.

I was trying to set a random seed outside of `Simulator` but my data was not being randomised properly.

Then I remembered that you mention in your documentation that calling `Simulator` sets a random seed so that the simulations are replicable.

Because `Simulator` resets the random seed each time it's called, naively doing the following:
```
horizon     <- 100L
simulations <- 100L
weights     <- c(0.9, 0.1, 0.1)
policy      <- EpsilonGreedyPolicy$new(epsilon = 0.1)
bandit      <- BasicBernoulliBandit$new(weights = weights)
agent       <- Agent$new(policy, bandit)

for (i in 1:2) {
  history <- Simulator$new(agent, horizon, simulations)$run()
  print(runif(1))
}
```
results in identical values from the two calls of `runif(1)`.

I came up with the following simple solution which works in my case (it sets a unique seed from the loop index):
```
for (i in 1:2) {
  history <- Simulator$new(agent, horizon, simulations, set_seed= i)$run()
  print(runif(1))
}
```
However, I wondered if there was a way for `Simulator` to only set its own internal random seed and not reset it globally each time it is called.

**Comment by robinvanemden** [comment]
Great catch! In my own research, I work mostly on code _within_ simulations, so I had not encountered this particular issue yet. However, the issue should have resolved in the latest commit. 

It adds two utility functions, `get_global_seed()` and `set_global_seed(x)`, that respectively get the global seed before starting a simulation, and restore the global seed afterwards.

**Comment by robinvanemden** [comment]
PS: I see that I am not able to submit to CRAN until the 6th:
"The submission server team is on vacation from Dec 20, 2019 to Jan 6, 2020"
Until then you can, of course, install the latest version with:
```
install.packages("devtools")
devtools::install_github('Nth-iteration-labs/contextual')
```
